Add Yandex Music support
TopiSenpai/LavaSrc pull request #19
Opened 2022-10-17 08:46 UTC by AgutinVBoy

This is a new source manager for Yandex music. 

It supports songs, albums, playlists, artists and podcasts. Reqiures Token.

- `yasearch:Let's Get It Started`
- https://music.yandex.ru/album/7091037/track/767978
- https://music.yandex.ru/album/7091037
- https://music.yandex.ru/users/music-blog/playlists/1103
- https://music.yandex.ru/artist/451

#### Yandex Music
```java
AudioPlayerManager playerManager = new DefaultAudioPlayerManager();

// create a new YandexMusicSourceManager with the token and register it
playerManager.registerSourceManager(new YandexMusicSourceManager("...", playerManager));
```

## Important information
Yandex Music is very location-dependent. You should either have a premium subscription or be located in one of the following countries:
- Azerbaijan
- Armenia
- Belarus
- Georgia
- Kazakhstan
- Kyrgyzstan
- Moldova
- Russia
- Tajikistan
- Turkmenistan
- Uzbekistan

Else you will only have access to podcasts.

## How to get token
1. (Optional) Open DevTools in your browser and on the Network tab enable trotlining.
2. Go to [https://oauth.yandex.ru/authorize?response_type=token&client_id=23cabbbdc6cd418abb4b39c32c41195d](https://oauth.yandex.ru/authorize?response_type=token&client_id=23cabbbdc6cd418abb4b39c32c41195d)
3. Authorize and grant access
4. The browser will redirect to the address like `https://music.yandex.ru/#access_token=AQAAAAAYc***&token_type=bearer&expires_in=31535645`. 
Very quickly there will be a redirect to another page, so you need to have time to copy the link. ![image](https://user-images.githubusercontent.com/68972811/196124196-a817b828-3387-4f70-a2b2-cdfdc71ce1f2.png)
5. Your token, what is after `access_token`.

2022-10-17 09:41 UTC, TopiSenpai requested changes
I just skimmed it & will give it a full review later once you addressed most of this stuff
but here are some points I noticed:
- update the readme
- `YandexMusicAudioTrack#getTrackTitle` has no usage
- there is no point in passing `songId` that's just the identifier. Other sources use the isrc here which is something different
- why do you load the resulting mp3 like this? You can just create an `PersistentHttpStream` & skip the whole `loadItem` stuff(see deezer)
- `YandexMusicAudioTrack` should process an `Mp3AudioTrack` if it's an mp3 track
- `YanddexMusicSourceManager` does not need the `AudioPlayerManager`
- please cleanup the regex code(call matcher.find after each other not weirdly in each other)
- `json.get("bla") == null` will always be false. use `json.get("bla").isNull()`
- `token` in the config should be renamed to something more descriptive
- how long are tokens valid? do they ever expire?
- can you provide me with some example json responses for endpoints?
- I don't think you need the `YandexMusicTrackLoadingException`
- for html parsing use `jsoup` instead of `indexOf` & `substring`
- is that sign key guaranteed to not update? might be better to not hardcode it
- please orient yourself on the code styling I use(no ifs without `{}` as an example)
- shouldn't the music search prefix be `ymsearch:`?

besides those points above cool thing I guess. It seems pretty niche for most people

If you have any questions feel free to ask

2022-10-17 11:45 UTC, TopiSenpai commented
> unfortunately, yandex music has no isrc. only IDs
then please remove it
> If I'm not mistaken, the token lives for one year. It cannot be refreshed automatically.
On the other hand, I heard that they live a very long time. Maybe lifetime.
please mention this in the docs
> I don't know :) I wrote yasearch because Yandex uses abbreviations for its products (Ya.Disk, Ya.Taxi, Ya.Music)
You use `Yandex Music` everywhere so I think it makes more sense
> Sure. Where can I send you responses? They are very large, so I don't think I should send them here. Maybe discord? (Eterna#9999)
you can just paste it as a file here or use https://hastebin.de

2022-10-17 12:14 UTC, AgutinVBoy commented
> then please remove it

songId is required to get link to mp3 (YandexMusicAudioTrack#getDownloadURL). 

> please mention this in the docs

ok

> You use Yandex Music everywhere so I think it makes more sense

ok, I'll change it.

> responses

[track success](https://hastebin.de/lekerorigu.yaml), [track failed](https://hastebin.de/agetehaceb.yaml), [track failed (wrong country)](https://hastebin.de/bokepapagu.yaml), [playlist success](https://hastebin.de/lozawomewa.yaml), [playlist failed 404](https://hastebin.de/ukidolevad.yaml), [playlist failed (wrong country)](https://hastebin.de/ajunezalit.yaml).

If you need more, I'll do it.

2022-10-17 12:52 UTC, AgutinVBoy commented
> you already pass the song id as identifier. there is no need to have it twice

Oh, I see. I forgot about that)

2022-10-17 13:09 UTC, AgutinVBoy commented
About matcher. Is this okay? 
```java
var matcher = URL_PATTERN.matcher(reference.identifier);
var playlist_matcher = URL_PLAYLIST_PATTERN.matcher(reference.identifier);
if (playlist_matcher.find()) {
    matcher = playlist_matcher;
} else if (!matcher.find()) {
    return null;
}
```

2022-10-17 13:13 UTC, TopiSenpai commented
why not
```java
var matcher = URL_PATTERN.matcher(reference.identifier);
if (matcher.find()) {
    // do stuff
    return
}

matcher = URL_PLAYLIST_PATTERN.matcher(reference.identifier);
if (matcher.find()) {
    // do stuff
    return
}
return null
```

2022-10-17 15:22 UTC, TopiSenpai commented on main/src/main/java/com/github/topisenpai/lavasrc/yandexmusic/YandexMusicSourceManager.java
> +    public static final Pattern URL_PLAYLIST_PATTERN = Pattern.compile("(https?://)?music\\.yandex\\.ru/(?<type1>users)/(?<identifier>[0-9A-Za-z@.-]+)/playlists/(?<identifier2>[0-9]+)/?");
```suggestion
    public static final Pattern URL_PLAYLIST_PATTERN = Pattern.compile("(https?://)?music\\.yandex\\.ru/users/(?<identifier>[0-9A-Za-z@.-]+)/playlists/(?<identifier2>[0-9]+)/?");
```

2022-10-17 15:27 UTC, TopiSenpai commented on main/src/main/java/com/github/topisenpai/lavasrc/yandexmusic/YandexMusicSourceManager.java
> +        if (json.isNull())
you can combine these ifs together

2022-10-17 15:39 UTC, TopiSenpai commented on main/src/main/java/com/github/topisenpai/lavasrc/yandexmusic/README.md
> +Else you will only have access to podcasts.
I'd rather have this in the root readme
you can hide some stuff with a details html block

2022-10-17 18:37 UTC, TopiSenpai commented on README.md
> +* [Yandex Music](https://music.yandex.ru) playlists/albums/songs/artists/podcasts/search results(Big thx to [AgutinVBoy](https://github.com/agutinvboy) for helping me)
```suggestion
* [Yandex Music](https://music.yandex.ru) playlists/albums/songs/artists/podcasts/search results(Thx to [AgutinVBoy](https://github.com/agutinvboy) for implementing it)
```

2022-10-17 18:51 UTC, AgutinVBoy commented on main/src/main/java/com/github/topisenpai/lavasrc/yandexmusic/YandexMusicSourceManager.java
> +        return HttpClientTools.fetchResponseLines(this.httpInterfaceManager.getInterface(), request, "UTF-8")[0];
in lower case? If so, then it's resolved

2022-10-17 20:36 UTC, TopiSenpai commented on main/src/main/java/com/github/topisenpai/lavasrc/yandexmusic/YandexMusicSourceManager.java
> +        return HttpClientTools.fetchResponseLines(this.httpInterfaceManager.getInterface(), request, "UTF-8")[0];
not exactly

> looking at the lavaplayer code this actually something else

> name – Name of the operation to include in exception messages.

2022-10-18 10:35 UTC, TopiSenpai commented on main/src/main/java/com/github/topisenpai/lavasrc/yandexmusic/YandexMusicSourceManager.java
> +        return HttpClientTools.fetchResponseLines(this.httpInterfaceManager.getInterface(), request, "UTF-8")[0];
As an example
Just something descriptive

2022-10-18 10:41 UTC, AgutinVBoy commented on main/src/main/java/com/github/topisenpai/lavasrc/yandexmusic/YandexMusicSourceManager.java
> +        return HttpClientTools.fetchResponseLines(this.httpInterfaceManager.getInterface(), request, "UTF-8")[0];
done

2022-10-18 11:13 UTC, TopiSenpai requested changes

2022-10-18 11:13 UTC, TopiSenpai commented on main/src/main/java/com/github/topisenpai/lavasrc/yandexmusic/YandexMusicAudioTrack.java
> +            throw new FriendlyException("No download URL found for track " + id, FriendlyException.Severity.COMMON, null);
you should throw `IllegalStateException` here

2022-10-18 11:13 UTC, TopiSenpai commented on main/src/main/java/com/github/topisenpai/lavasrc/yandexmusic/YandexMusicAudioTrack.java
> +            throw new FriendlyException("No download URL found for track " + id, FriendlyException.Severity.COMMON, null);
you should throw `IllegalStateException` here

2022-10-18 11:13 UTC, TopiSenpai commented on main/src/main/java/com/github/topisenpai/lavasrc/yandexmusic/YandexMusicAudioTrack.java
> +        Document doc = Jsoup.parse(downloadInfo, "", Parser.xmlParser());
var

2022-10-18 11:13 UTC, TopiSenpai commented on main/src/main/java/com/github/topisenpai/lavasrc/yandexmusic/YandexMusicAudioTrack.java
> +        for (byte b : digest)
missing `{}`

2022-10-18 11:13 UTC, TopiSenpai commented on main/src/main/java/com/github/topisenpai/lavasrc/yandexmusic/YandexMusicAudioTrack.java
> +        var md = MessageDigest.getInstance("MD5");
can we reuse the md5 instance?

2022-10-18 12:02 UTC, AgutinVBoy commented on main/src/main/java/com/github/topisenpai/lavasrc/yandexmusic/YandexMusicAudioTrack.java
> +        var md = MessageDigest.getInstance("MD5");
I think so

2022-10-18 16:38 UTC, AgutinVBoy commented on main/src/main/java/com/github/topisenpai/lavasrc/yandexmusic/YandexMusicAudioTrack.java
> +        var md = MessageDigest.getInstance("MD5");
Do you think it should be written elsewhere?

2022-10-18 17:41 UTC, TopiSenpai commented on main/src/main/java/com/github/topisenpai/lavasrc/yandexmusic/YandexMusicAudioTrack.java
> +        var md = MessageDigest.getInstance("MD5");
It doesn't really matter
Ignore I said anything :^)

2022-10-21 14:27 UTC, TopiSenpai commented
I can't really test this as I don't have an account there and tbh I don't want to create one either
Do you have a bot/node running with this or want to give me an access token?
Either works for me I guess

2022-10-21 14:31 UTC, TopiSenpai commented
code-wise it looks fine at least

2022-10-21 17:16 UTC, AgutinVBoy commented
Sure. You can join in my [discord server](https://discord.gg/FA9d7MQk) 
Prefixes `>>` or `/2`

2022-10-21 18:54 UTC, TopiSenpai requested changes
looks fine to me now
how does it behave with big playlists?
does it load the full or does it need pagination?

2022-10-21 19:11 UTC, TopiSenpai approved these changes
nice work

2022-10-21 19:12 UTC, merged