Some fixes for yandex music which led to an error when loading a track or playlist
TopiSenpai/LavaSrc pull request #31
Opened 2022-11-16 12:23 UTC by BrokenFG

Fix error when track doesn't have cover
Fix error when track is not available
Fix error when track doesn't include in any albums (for example user uploaded track manually)

2022-11-16 12:43 UTC, TopiSenpai requested changes
else looks good. I assume you tested this as i can't

2022-11-16 12:43 UTC, TopiSenpai commented on main/src/main/java/com/github/topisenpai/lavasrc/yandexmusic/YandexMusicSourceManager.java
> +        if (json.get("available").text().equals("false") || json.get("albums").values().isEmpty()) {
you should use `json.get("available").asBoolean` here

2022-11-16 12:56 UTC, BrokenFG commented
> > Fix error when track doesn't include in any albums (for example user uploaded track manually)
> 
> can we not stream it in this case?

We won't, we check the track for availability and for its presence in the album, if any of these conditions are not met, we skip this track

2022-11-16 13:02 UTC, BrokenFG commented
> I assume you tested this as i can't

I came across these errors when trying to play my playlist, after these changes everything works fine for me

2022-11-16 13:10 UTC, BrokenFG commented on main/src/main/java/com/github/topisenpai/lavasrc/yandexmusic/YandexMusicSourceManager.java
> +        if (json.get("available").text().equals("false") || json.get("albums").values().isEmpty()) {
https://github.com/TopiSenpai/LavaSrc/pull/31/commits/a4360ebb824258bd84b42216cbea910a05ac3dd5

2022-11-16 16:53 UTC, TopiSenpai approved these changes
looks good from me. will wait for @AgutinVBoy before merging

2022-11-16 19:22 UTC, AgutinVBoy requested changes

2022-11-16 19:22 UTC, AgutinVBoy commented on main/src/main/java/com/github/topisenpai/lavasrc/yandexmusic/YandexMusicSourceManager.java
> +                tracks.add(this.parseTrack(track));
```suggestion
                tracks.add(parsedTrack);
```

2022-11-17 11:47 UTC, BrokenFG commented
> Can you provide a case? When I tested the library, I could not get any local track in response.

track must be uploaded to the account whose token is being used, idk what can i provide except of returning json result
https://pastebin.com/c15QWcy3

2022-11-17 11:50 UTC, BrokenFG commented on main/src/main/java/com/github/topisenpai/lavasrc/yandexmusic/YandexMusicSourceManager.java
> +                tracks.add(this.parseTrack(track));
Sorry, I have no idea how I could've missed this

2022-11-17 11:50 UTC, BrokenFG commented on main/src/main/java/com/github/topisenpai/lavasrc/yandexmusic/YandexMusicSourceManager.java
> +                tracks.add(this.parseTrack(track));
Sorry, I have no idea how I could've missed this

2022-11-17 13:13 UTC, AgutinVBoy approved these changes

2022-11-17 15:00 UTC, merged

2022-11-17 15:03 UTC, TopiSenpai commented
thx