Feature/delegating lookup
TopiSenpai/LavaSrc pull request #44
Opened 2023-01-02 00:09 UTC by dscalzi

The DelegatedAudioLookup function allows the track lookup behavior to be injectable by the client application. This may be desired when isrc/name match lookup is not good enough, and additional logic needs to be applied.

Sample usage:

```java
playerManager.registerSourceManager(new SpotifySourceManager(
		null,
		g.getSpotifyClientId(),
		g.getSpotifyClientSecret(),
		g.getSpotifyCountryCode(),
		playerManager,
		mirroringAudioTrack -> {
			final String ytsearch = "ytsearch:";

			// Try by isrc
			AudioItem item = AudioReference.NO_TRACK;
			if(mirroringAudioTrack.getISRC() != null) {
				item = MirroringAudioTrack.loadItem(
						ytsearch + mirroringAudioTrack.getISRC(),
						mirroringAudioTrack.getMirroringSourceManager());
				String title = null;
				if(item instanceof InternalAudioTrack casted) {
					title = casted.getInfo().title;
				}
				else if(item instanceof AudioPlaylist casted) {
					title = casted.getTracks().get(0).getInfo().title;
				}
				if(title != null) {
					if(!title.toLowerCase().contains(mirroringAudioTrack.getInfo().title.toLowerCase())) {
						log.info("Title Mismatch, Expected: {}. Actual: {}.", mirroringAudioTrack.getInfo().title, title);
						item = AudioReference.NO_TRACK;
					}
				}
			}
			// Try name + isrc
			if(item == AudioReference.NO_TRACK) {
				item = MirroringAudioTrack.loadItem(
						ytsearch + mirroringAudioTrack.getInfo().title + " " + mirroringAudioTrack.getISRC(),
						mirroringAudioTrack.getMirroringSourceManager());
			}

			if(item == AudioReference.NO_TRACK) {
				log.error("Failed to find track");
			}

			return item;
		}
));
```

2023-01-02 10:43 UTC, TopiSenpai requested changes

2023-01-02 10:43 UTC, TopiSenpai commented on build.gradle
> +    version "3.2.0"
please let me do this

2023-01-02 10:43 UTC, TopiSenpai commented on main/src/main/java/com/github/topisenpai/lavasrc/applemusic/AppleMusicSourceManager.java
> +    public AppleMusicSourceManager(String[] providers, String mediaAPIToken, String countryCode, AudioPlayerManager audioPlayerManager, DelegatedAudioLookup delegatedAudioLookup) {
what is the point of `providers` here?
it's not being used anyway

2023-01-02 10:43 UTC, TopiSenpai commented on main/src/main/java/com/github/topisenpai/lavasrc/mirror/MirroringAudioTrack.java
> +        if (this.sourceManager.getDelegatedAudioLookup() == null) {
why not implement your `DelegatedAudioLookup` interface with a default implementation which takes the providers?

this code could look much simpler like this

2023-01-02 10:43 UTC, TopiSenpai commented on main/src/main/java/com/github/topisenpai/lavasrc/spotify/SpotifySourceManager.java
> +    public SpotifySourceManager(String[] providers, String clientId, String clientSecret, String countryCode, AudioPlayerManager audioPlayerManager, DelegatedAudioLookup delegatedAudioLookup) {
`providers` has no point here either

2023-01-02 10:43 UTC, TopiSenpai commented on main/src/main/java/com/github/topisenpai/lavasrc/mirror/DelegatedAudioLookup.java
> +public interface DelegatedAudioLookup extends Function<MirroringAudioTrack, AudioItem> {
perhaps this should be named `MirroringAudioTrackLookup`?

2023-01-02 11:44 UTC, dscalzi commented on main/src/main/java/com/github/topisenpai/lavasrc/applemusic/AppleMusicSourceManager.java
> +    public AppleMusicSourceManager(String[] providers, String mediaAPIToken, String countryCode, AudioPlayerManager audioPlayerManager, DelegatedAudioLookup delegatedAudioLookup) {
The other constructor flows into this one which then calls the super method. Typically I prefer to just have one constructor with logic and have the others just flow in. I could add a third overload for convenience.

2023-01-02 11:46 UTC, dscalzi commented on main/src/main/java/com/github/topisenpai/lavasrc/mirror/MirroringAudioTrack.java
> +        if (this.sourceManager.getDelegatedAudioLookup() == null) {
So define that in the MirroringAudioSourceManager if the delegatedAudioLookup is null, then just always invoke it here?

2023-01-02 11:48 UTC, dscalzi commented on main/src/main/java/com/github/topisenpai/lavasrc/mirror/DelegatedAudioLookup.java
> +public interface DelegatedAudioLookup extends Function<MirroringAudioTrack, AudioItem> {
I'm fine with whatever name, the rational behind this one was that the responsability to load the audio would be delegated to the application. This works fine also though as it mirrors the existing constructs.

2023-01-02 11:50 UTC, TopiSenpai commented on main/src/main/java/com/github/topisenpai/lavasrc/mirror/MirroringAudioTrack.java
> +        if (this.sourceManager.getDelegatedAudioLookup() == null) {
`getDelegatedAudioLookup` should never be able to be `null` in the first place.
You can just provide a default implementation for `DelegatedAudioLookup` using the providers

2023-01-02 11:51 UTC, TopiSenpai commented on main/src/main/java/com/github/topisenpai/lavasrc/applemusic/AppleMusicSourceManager.java
> +    public AppleMusicSourceManager(String[] providers, String mediaAPIToken, String countryCode, AudioPlayerManager audioPlayerManager, DelegatedAudioLookup delegatedAudioLookup) {
2 constructors are enough. You don't need providers in here at all. Just make an implementation of `DelegatedAudioLookup` with providers

2023-01-02 12:09 UTC, dscalzi commented on main/src/main/java/com/github/topisenpai/lavasrc/applemusic/AppleMusicSourceManager.java
> +    public AppleMusicSourceManager(String[] providers, String mediaAPIToken, String countryCode, AudioPlayerManager audioPlayerManager, DelegatedAudioLookup delegatedAudioLookup) {
pushed

2023-01-02 12:10 UTC, dscalzi commented on main/src/main/java/com/github/topisenpai/lavasrc/applemusic/AppleMusicSourceManager.java
> +    public AppleMusicSourceManager(String[] providers, String mediaAPIToken, String countryCode, AudioPlayerManager audioPlayerManager, DelegatedAudioLookup delegatedAudioLookup) {
the only problem with that is I have to remove getProviders which technically is a breaking change.

2023-01-02 12:14 UTC, dscalzi commented on main/src/main/java/com/github/topisenpai/lavasrc/applemusic/AppleMusicSourceManager.java
> +    public AppleMusicSourceManager(String[] providers, String mediaAPIToken, String countryCode, AudioPlayerManager audioPlayerManager, DelegatedAudioLookup delegatedAudioLookup) {
I could restore the variable but it makes this a bit more convoluted than it needs to be

2023-01-02 13:44 UTC, TopiSenpai commented on main/src/main/java/com/github/topisenpai/lavasrc/applemusic/AppleMusicSourceManager.java
> +    public AppleMusicSourceManager(String[] providers, String mediaAPIToken, String countryCode, AudioPlayerManager audioPlayerManager, DelegatedAudioLookup delegatedAudioLookup) {
I'm fine with that. That method i most likely not used by anyone

2023-01-03 08:52 UTC, TopiSenpai requested changes

2023-01-03 08:52 UTC, TopiSenpai commented on main/src/main/java/com/github/topisenpai/lavasrc/mirror/MirroringAudioSourceManager.java
> +    protected static MirroringAudioTrackLookup defaultMirroringAudioTrackLookup(final String[] providers) {
I'd prefer this to be in it's own class

2023-01-03 08:52 UTC, TopiSenpai commented on main/src/main/java/com/github/topisenpai/lavasrc/mirror/MirroringAudioTrack.java
> +    public String getTrackTitle() {
this should go into the other class aswell

2023-01-03 08:52 UTC, TopiSenpai commented on main/src/main/java/com/github/topisenpai/lavasrc/mirror/MirroringAudioTrack.java
> +    public MirroringAudioSourceManager getMirroringSourceManager() {
I don't think this method is needed

2023-01-03 09:43 UTC, dscalzi commented on main/src/main/java/com/github/topisenpai/lavasrc/mirror/MirroringAudioTrack.java
> +    public MirroringAudioSourceManager getMirroringSourceManager() {
it's so that custom lookups can get the manager without doing a cast

2023-01-04 02:10 UTC, dscalzi commented on main/src/main/java/com/github/topisenpai/lavasrc/mirror/MirroringAudioTrack.java
> +    public MirroringAudioSourceManager getMirroringSourceManager() {
I'd like to leave this here as an API level method. I'm not a fan of forcing implementing applications to cast, as it creates an implicit dependency on the implementation details. If that implementation class ever changes, you will not know until runtime. Specifically required for invoking loadItem 
```java
track = MirroringAudioTrackLookupUtil.loadItem(provider, mirroringAudioTrack.getMirroringSourceManager());
```

2023-01-05 18:42 UTC, TopiSenpai approved these changes
I moved & renamed some minor stuff. Like this it should be good to go. Let me know your thoughts

2023-01-05 20:40 UTC, TopiSenpai commented
yeah that was more or less intended. You can hide whitespace changes here
![image](https://user-images.githubusercontent.com/15636011/210875826-64fa9787-4d15-4727-b876-486c2bf4c03e.png)

2023-01-06 05:29 UTC, dscalzi commented
Works for me, go ahead and merge.

As a side note, 4 spaces is much more standard than using tabs, but feel free to use whatever you prefer.

2023-01-06 13:26 UTC, merged

2023-01-06 13:48 UTC, TopiSenpai commented
ty for the contribution